#!/bin/sh

# Find the line in "xrandr -q --verbose" output that contains current screen orientation and "strip" out current orientation.

rotation="$(xrandr -q --verbose | grep 'connected' | egrep -o  '\) (normal|left|inverted|right) \(' | egrep -o '(normal|left|inverted|right)')"

# Using current screen orientation proceed to rotate screen and input devices.

case "$rotation" in
    normal)
    # rotate to the left
    xrandr -o left
    xsetwacom set "Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus" rotate ccw
    xsetwacom set "Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser" rotate ccw
    xinput set-prop "Wacom Co.,Ltd. Pen and multitouch sensor Finger" "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
    ;;
    left)
    # rotate to inverted
    xrandr -o inverted
    xsetwacom set "Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus" rotate half
    xsetwacom set "Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser" rotate half
    xinput set-prop "Wacom Co.,Ltd. Pen and multitouch sensor Finger" "Coordinate Transformation Matrix" -1 0 1 0 -1 1 0 0 1
    ;;
    inverted)
    # rotate to the right
    xrandr -o right
    xsetwacom set "Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus" rotate cw
    xsetwacom set "Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser" rotate cw
    xinput set-prop "Wacom Co.,Ltd. Pen and multitouch sensor Finger" "Coordinate Transformation Matrix" 0 1 0 -1 0 1 0 0 1
    ;;
    right)
    # rotate to normal
    xrandr -o normal
    xsetwacom set "Wacom Co.,Ltd. Pen and multitouch sensor Pen stylus" rotate none
    xsetwacom set "Wacom Co.,Ltd. Pen and multitouch sensor Pen eraser" rotate none
    xinput set-prop "Wacom Co.,Ltd. Pen and multitouch sensor Finger" "Coordinate Transformation Matrix" 1 0 0 0 1 0 0 0 1
    ;;
esac
